<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'BK2K\\BootstrapPackage\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'In2code\\Powermail\\' => array($typo3InstallDir . 'typo3conf/ext/powermail/Classes'),
    'MASK\\Mask\\' => array($typo3InstallDir . 'typo3conf/ext/mask/Classes'),
    'Net2Typo\\StudentMgmt\\' => array($typo3InstallDir . 'typo3conf/ext/student_mgmt/Classes'),
    'Net2typo\\Kindergartensitepackage\\' => array($typo3InstallDir . 'typo3conf/ext/kindergartensitepackage/Classes'),
    'T3\\Dce\\' => array($typo3InstallDir . 'typo3conf/ext/dce/Classes'),
    'TYPO3\\CMS\\ContentBlocks\\' => array($typo3InstallDir . 'typo3conf/ext/content_blocks/Classes'),
    'Websedit\\WeCookieConsent\\' => array($typo3InstallDir . 'typo3conf/ext/we_cookie_consent/Classes'),
);
